<?php require 'templates/header.phtml' ?>

<div>
    <h1>Lista de categorias: </h1>
    <ul>
        <?php session_start(); ?>
        <?php foreach($categories as $category): ?>
            <li>
                <div>
                    <h3><?=$category->category_name?></h3>
                    <div class="btns"><button><a href="category/<?= $category->category_id ?>">Ver categoría</a></button><button class="<?php if(!isset($_SESSION['USER_ID'])): ?>off <?php endif ?>"><a href="editar-cat/<?= $category->category_id ?>">Editar</a></button><button class="<?php if(!isset($_SESSION['USER_ID'])): ?>off <?php endif ?>"><a href="delete-category/<?=$category->category_id?>">Eliminar</a></button></div>
                </div>
            </li>
        <?php endforeach ?>
    </ul>
</div>
<div class='btns'>
    <button><a href='enter-category'>Agregar nueva categoría</a></button>
</div>

<?php require 'templates/footer.phtml' ?>