<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <base href="<?= BASE_URL ?>">
    <link rel="stylesheet" href="css/organia.css">
    <title>Organia</title>
</head>

<body>
    <div class="totalgrid">
    <header>
        <img id="logo" src="img/organialogo.png" alt="organialogo">
    </header>

    <nav id="menu">
        <div>
            <button><a href="<?=BASE_URL?>">Home</a></button>
        </div>

        <div>
            <button><a href='./categories'>Ver categorías</a></button>
        </div>

        <div>
        <button><a href='./productsList'>Ver Productos</a></button>
        </div>

        <div>
        <button><a href='./panel'>Panel de Administrador</a></button>
        </div>
    </nav>

    <main>