
<?php require 'templates/header.phtml'; ?>

<h2>Login</h2>

<form id= "form" action="loginUser" method="POST">
   <input type="text" name="user" placeholder="Usuario" required>
   <input type="password" name="password" placeholder="Contraseña" required>
   
   <div class='btns'>
      <button type="submit"> Ingresar </button>
   </div>
</form>

<?php require 'templates/footer.phtml'; ?>